language: node_js
node_js:
  - 9

sudo: false


install:
  - npm install

script:
  - npm run build
  - npm run test

#after_success:
#    - npm run coveralls

#after_success:
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
