language: node_js
node_js:
  - 9

sudo: required

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

addons:
  chrome: stable

install:
  - npm install

script:
  - npm run build
  - npm run test

#after_success:
#    - npm run coveralls

#after_success:
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
