language: node_js
node_js:
- 10
sudo: required
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
install:
- npm install
- npm run bootstrap
- node_modules/protractor/bin/webdriver-manager update --github_token=$PROTRACTOR_GITHUB_TOKEN
script:
- npm run build
- npm run test
deploy:
  skip_cleanup: true
  provider: npm
  email: gabi.grinberg@gmail.com
  api_key:
    secure: k2AsJV1hxT9epsoa2xQIbey5Nqv2Si7STj+eds0jtybQ4uxHiVjCxwFlTdoBD7PjnixrgDtStVRn4xGAur19+m5phtPqz7sTrhrpqeGSYNgGPMIs46DGXPIFs3RZhOP7cJQecSePvjQeXU7KKaP4Uw14H+G+oMQC9N4Nhn8m6jCzCZ+ywJe9VD/JkiTtjQchm3HBfqmzDrnzSeLR8OUeWyr/FKMnD689lyYydfEg9MvIoV5PgSeLc4MsSTANqiFb+InVRUd6J9fB0W8ElMdndSYzzh7sJmseLjfypHaOGdwsgzRSKe5Xh366dlgYGmN543Z09XFvq81TramQ9HGPcCCB1g+db0yf88vtyok3FRc/RDuMtVm9PaTtpzqbl5huqH7IQJy7VlPNQPJomPEZ64iDoxyTd/gAqKy2cjj/sfTJuad/w9q8GVGx0vdQphRkznJw5qg4n7xJVcafVkf7NtbLDfVerSHUVOkh1bUQ/MIi4eEt3niRLIXWWAJt66DZuW0O2JylQTEYhF5Mykj4Br5/1TPkYV/eRdPg08x13hJhF6ncTSoWADRN+KBy0/V0orKgzJgU9SH8PyxVIzdawOIUZWm62eJmJSHAt07JVkf0sGy3miJj0U4ZmHPlgGD8HPnVr6V1zmujQ1hvsdpHueu+UkAOPKFeWtOv3oBdPwo=
  on:
    tags: true
    repo: wix-incubator/unidriver
